-- ============================================================================
-- Cocktail Demo · Initial Schema
-- Run this once in your Supabase project (SQL Editor → New query → Run).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Restaurants (tenants)
-- ---------------------------------------------------------------------------
create table if not exists restaurants (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  name text not null,
  default_lang text default 'en' check (default_lang in ('en', 'he')),
  brand_color text,
  logo_url text,
  created_at timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- Restaurant membership (links auth.users to restaurants)
-- ---------------------------------------------------------------------------
create table if not exists restaurant_members (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid references restaurants(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  role text default 'manager' check (role in ('owner', 'manager', 'staff')),
  created_at timestamptz default now(),
  unique (restaurant_id, user_id)
);

-- ---------------------------------------------------------------------------
-- Cocktails (menu items)
-- ---------------------------------------------------------------------------
create table if not exists cocktails (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid references restaurants(id) on delete cascade not null,
  slug text not null,
  status text default 'draft' check (status in ('draft', 'published', 'archived')),
  title_en text not null,
  title_he text,
  subtitle_en text default 'Components Breakdown',
  subtitle_he text default 'פירוט המרכיבים',
  tagline_en text,
  tagline_he text,
  category text not null check (category in ('citrus', 'smoky', 'bitter', 'sweet', 'mocktail')),
  hero_image text not null,
  hero_prompt text,
  flavor jsonb default '{"sweet":2,"bitter":2,"citrus":2,"smoky":2,"herbal":2}'::jsonb,
  bartender_note_en text,
  bartender_note_he text,
  bartender_name text,
  dietary jsonb default '{"vegan":true,"glutenFree":true,"alcoholFree":false}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (restaurant_id, slug)
);

-- ---------------------------------------------------------------------------
-- Cocktail layers (3D breakdown components)
-- ---------------------------------------------------------------------------
create table if not exists cocktail_layers (
  id uuid primary key default gen_random_uuid(),
  cocktail_id uuid references cocktails(id) on delete cascade not null,
  layer_id text not null,
  image text not null,
  y numeric not null,
  z numeric not null,
  scale numeric not null,
  float_amp numeric not null,
  float_speed numeric not null,
  parallax_factor numeric not null,
  generation_prompt text,
  position int not null,
  unique (cocktail_id, layer_id)
);

-- ---------------------------------------------------------------------------
-- Cocktail labels (ingredient labels in breakdown)
-- ---------------------------------------------------------------------------
create table if not exists cocktail_labels (
  id uuid primary key default gen_random_uuid(),
  cocktail_id uuid references cocktails(id) on delete cascade not null,
  label_id text not null,
  number text not null,
  name_en text not null,
  name_he text,
  description_en text not null,
  description_he text,
  origin_en text,
  origin_he text,
  layer_id text not null,
  position int not null,
  unique (cocktail_id, label_id)
);

-- ---------------------------------------------------------------------------
-- Events (analytics)
-- ---------------------------------------------------------------------------
create table if not exists events (
  id bigint generated by default as identity primary key,
  restaurant_id uuid references restaurants(id) on delete cascade not null,
  cocktail_id uuid references cocktails(id) on delete set null,
  event_type text not null check (event_type in ('view', 'hover_layer', 'share', 'favorite', 'order')),
  metadata jsonb,
  session_id text,
  created_at timestamptz default now()
);

create index if not exists idx_events_restaurant_created
  on events (restaurant_id, created_at desc);
create index if not exists idx_events_cocktail
  on events (cocktail_id, event_type);

-- ---------------------------------------------------------------------------
-- Row Level Security (RLS)
-- ---------------------------------------------------------------------------
alter table restaurants enable row level security;
alter table restaurant_members enable row level security;
alter table cocktails enable row level security;
alter table cocktail_layers enable row level security;
alter table cocktail_labels enable row level security;
alter table events enable row level security;

-- Restaurants: public read, members can update their own
drop policy if exists "Restaurants are viewable by everyone" on restaurants;
create policy "Restaurants are viewable by everyone"
  on restaurants for select using (true);

drop policy if exists "Members can update their restaurant" on restaurants;
create policy "Members can update their restaurant"
  on restaurants for update using (
    exists (
      select 1 from restaurant_members
      where restaurant_members.restaurant_id = restaurants.id
        and restaurant_members.user_id = auth.uid()
    )
  );

-- Restaurant members: users see their own memberships
drop policy if exists "Users see their own memberships" on restaurant_members;
create policy "Users see their own memberships"
  on restaurant_members for select using (user_id = auth.uid());

-- Cocktails: published are public, drafts only to members
drop policy if exists "Published cocktails are viewable by everyone" on cocktails;
create policy "Published cocktails are viewable by everyone"
  on cocktails for select using (status = 'published');

drop policy if exists "Members see all cocktails of their restaurant" on cocktails;
create policy "Members see all cocktails of their restaurant"
  on cocktails for select using (
    exists (
      select 1 from restaurant_members
      where restaurant_members.restaurant_id = cocktails.restaurant_id
        and restaurant_members.user_id = auth.uid()
    )
  );

drop policy if exists "Members can write cocktails" on cocktails;
create policy "Members can write cocktails"
  on cocktails for all using (
    exists (
      select 1 from restaurant_members
      where restaurant_members.restaurant_id = cocktails.restaurant_id
        and restaurant_members.user_id = auth.uid()
    )
  );

-- Layers + labels: read with cocktail visibility
drop policy if exists "Layers visible if cocktail is visible" on cocktail_layers;
create policy "Layers visible if cocktail is visible"
  on cocktail_layers for select using (
    exists (
      select 1 from cocktails
      where cocktails.id = cocktail_layers.cocktail_id
        and (
          cocktails.status = 'published'
          or exists (
            select 1 from restaurant_members
            where restaurant_members.restaurant_id = cocktails.restaurant_id
              and restaurant_members.user_id = auth.uid()
          )
        )
    )
  );

drop policy if exists "Members can write layers" on cocktail_layers;
create policy "Members can write layers"
  on cocktail_layers for all using (
    exists (
      select 1 from cocktails
      join restaurant_members on restaurant_members.restaurant_id = cocktails.restaurant_id
      where cocktails.id = cocktail_layers.cocktail_id
        and restaurant_members.user_id = auth.uid()
    )
  );

drop policy if exists "Labels visible if cocktail is visible" on cocktail_labels;
create policy "Labels visible if cocktail is visible"
  on cocktail_labels for select using (
    exists (
      select 1 from cocktails
      where cocktails.id = cocktail_labels.cocktail_id
        and (
          cocktails.status = 'published'
          or exists (
            select 1 from restaurant_members
            where restaurant_members.restaurant_id = cocktails.restaurant_id
              and restaurant_members.user_id = auth.uid()
          )
        )
    )
  );

drop policy if exists "Members can write labels" on cocktail_labels;
create policy "Members can write labels"
  on cocktail_labels for all using (
    exists (
      select 1 from cocktails
      join restaurant_members on restaurant_members.restaurant_id = cocktails.restaurant_id
      where cocktails.id = cocktail_labels.cocktail_id
        and restaurant_members.user_id = auth.uid()
    )
  );

-- Events: anyone can insert (anonymous tracking), only members can read
drop policy if exists "Anyone can insert events" on events;
create policy "Anyone can insert events"
  on events for insert with check (true);

drop policy if exists "Members can read their restaurant events" on events;
create policy "Members can read their restaurant events"
  on events for select using (
    exists (
      select 1 from restaurant_members
      where restaurant_members.restaurant_id = events.restaurant_id
        and restaurant_members.user_id = auth.uid()
    )
  );

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists update_cocktails_updated_at on cocktails;
create trigger update_cocktails_updated_at
  before update on cocktails
  for each row execute function update_updated_at_column();

-- ---------------------------------------------------------------------------
-- Seed: the "Diner" restaurant
-- ---------------------------------------------------------------------------
insert into restaurants (slug, name, default_lang)
values ('diner', 'Diner', 'en')
on conflict (slug) do nothing;
